// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8tHxGc7fvE80mujdNe39op3D90XTpoig',
    appId: '1:944984505105:web:ef9941d1639149eddaaab0',
    messagingSenderId: '944984505105',
    projectId: 'reclaim-space-df557',
    authDomain: 'reclaim-space-df557.firebaseapp.com',
    storageBucket: 'reclaim-space-df557.firebasestorage.app',
    measurementId: 'G-TVBFEYN5H9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhKaXjD1X-9X9WWCkaRuoDh_h0NDM1gi0',
    appId: '1:944984505105:android:fffea3cb4606a71ddaaab0',
    messagingSenderId: '944984505105',
    projectId: 'reclaim-space-df557',
    storageBucket: 'reclaim-space-df557.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKyJwuuhnSq8EDk3f1UFvqTpZmxvqYJDE',
    appId: '1:944984505105:ios:8a0f8c0ba741395cdaaab0',
    messagingSenderId: '944984505105',
    projectId: 'reclaim-space-df557',
    storageBucket: 'reclaim-space-df557.firebasestorage.app',
    iosBundleId: 'com.example.reclaimSpace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKyJwuuhnSq8EDk3f1UFvqTpZmxvqYJDE',
    appId: '1:944984505105:ios:8a0f8c0ba741395cdaaab0',
    messagingSenderId: '944984505105',
    projectId: 'reclaim-space-df557',
    storageBucket: 'reclaim-space-df557.firebasestorage.app',
    iosBundleId: 'com.example.reclaimSpace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8tHxGc7fvE80mujdNe39op3D90XTpoig',
    appId: '1:944984505105:web:7a0811b05a3464d8daaab0',
    messagingSenderId: '944984505105',
    projectId: 'reclaim-space-df557',
    authDomain: 'reclaim-space-df557.firebaseapp.com',
    storageBucket: 'reclaim-space-df557.firebasestorage.app',
    measurementId: 'G-9ZJY9N9FV8',
  );
}
