name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # ✅ Step 1: Checkout repo
      - uses: actions/checkout@v4

      # ✅ Step 2: Set up Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # Set your version here

      # ✅ Step 3: Get dependencies
      - run: flutter pub get
        working-directory: ./reclaim_space

      # ✅ Step 4: Build web
      - run: flutter build web
        working-directory: ./reclaim_space

      # ✅ Step 5: Deploy to Firebase Hosting
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_RECLAIM_SPACE_DF557 }}
          channelId: live
          projectId: reclaim-space-df557
          entrypoint: ./reclaim_space
